### ISSUE TITLE
Failed to update microsoft CVE data

### ISSUE THREAD

**Issue by kazkun** [knqyf263/gost#23]
I fetched the Microsoft's CVE to update gost.sqlite3 DB.
`gost fetch microsoft --apikey=xxxxxxxxxxxxx`
It said following error.
```
EROR[06-12|16:20:49] Failed to insert. dbpath=/something/gost.sqlite3 err="Failed to insert Microsoft CVE data. err: Failed to delete old records. err: FOREIGN KEY constraint failed"
Failed to insert Microsoft CVE data. err: Failed to delete old records. err: FOREIGN KEY constraint failed
```

**Comment by dtmkalayci** [comment]
some error... 

0 / 5457 [_____________________________________________________________________________] 0.00% ? p/st=2019-08-22T05:54:41+0000 lvl=eror msg="Failed to insert." dbpath=/vuls/gost.sqlite3 err="Failed to insert Microsoft CVE data. err: Failed to delete old records. err: FOREIGN KEY constraint failed"
Failed to insert Microsoft CVE data. err: Failed to delete old records. err: FOREIGN KEY constraint failed

**Comment by maj0rmil4d** [comment]
Hi , I faced the same error , please help

**Comment by mai346** [comment]
https://github.com/knqyf263/gost/blob/master/db/microsoft.go#L22
https://github.com/knqyf263/gost/blob/master/db/microsoft.go#L75

How about changing “RedhatCVE” to “MicrosoftCVE”?

**Comment by kotakanbe** [comment]
Closed because it cannot be reproduced.
