### ISSUE TITLE
make install failure

### ISSUE THREAD

**Issue by kerub77** [knqyf263/gost#32]
$ mkdir -p $GOPATH/src/github.com/knqyf263
$ cd $GOPATH/src/github.com/knqyf263
$ git clone https://github.com/knqyf263/gost.git
$ cd gost
$ make install

../../go-redis/redis/cluster.go:16:2: cannot find package "github.com/go-redis/redis/v7/internal" in any of:
        /usr/local/go/src/github.com/go-redis/redis/v7/internal (from $GOROOT)
        /root/go/src/github.com/go-redis/redis/v7/internal (from $GOPATH)
../../go-redis/redis/ring.go:14:2: cannot find package "github.com/go-redis/redis/v7/internal/consistenthash" in any of:
        /usr/local/go/src/github.com/go-redis/redis/v7/internal/consistenthash (from $GOROOT)
        /root/go/src/github.com/go-redis/redis/v7/internal/consistenthash (from $GOPATH)
../../go-redis/redis/cluster.go:17:2: cannot find package "github.com/go-redis/redis/v7/internal/hashtag" in any of:
        /usr/local/go/src/github.com/go-redis/redis/v7/internal/hashtag (from $GOROOT)
        /root/go/src/github.com/go-redis/redis/v7/internal/hashtag (from $GOPATH)
../../go-redis/redis/cluster.go:18:2: cannot find package "github.com/go-redis/redis/v7/internal/pool" in any of:
        /usr/local/go/src/github.com/go-redis/redis/v7/internal/pool (from $GOROOT)
        /root/go/src/github.com/go-redis/redis/v7/internal/pool (from $GOPATH)
../../go-redis/redis/cluster.go:19:2: cannot find package "github.com/go-redis/redis/v7/internal/proto" in any of:
        /usr/local/go/src/github.com/go-redis/redis/v7/internal/proto (from $GOROOT)
        /root/go/src/github.com/go-redis/redis/v7/internal/proto (from $GOPATH)
../../go-redis/redis/command.go:12:2: cannot find package "github.com/go-redis/redis/v7/internal/util" in any of:
        /usr/local/go/src/github.com/go-redis/redis/v7/internal/util (from $GOROOT)
        /root/go/src/github.com/go-redis/redis/v7/internal/util (from $GOPATH)
../../labstack/echo/middleware/basic_auth.go:8:2: cannot find package "github.com/labstack/echo/v4" in any of:
        /usr/local/go/src/github.com/labstack/echo/v4 (from $GOROOT)
        /root/go/src/github.com/labstack/echo/v4 (from $GOPATH)
cmd/debian.go:7:2: cannot find package "github.com/spf13/cobra" in any of:
        /usr/local/go/src/github.com/spf13/cobra (from $GOROOT)
        /root/go/src/github.com/spf13/cobra (from $GOPATH)
fetcher/microsoft.go:12:2: cannot find package "github.com/tealeg/xlsx" in any of:
        /usr/local/go/src/github.com/tealeg/xlsx (from $GOROOT)
        /root/go/src/github.com/tealeg/xlsx (from $GOPATH)
make: *** [vet] Error 123

**Comment by takuzoo3868** [comment]
@kerub77
Update Go to the latest version. plz :)

**Comment by kerub77** [comment]
Solved updating go.
thanks!
