### ISSUE TITLE
Error when running `gost fetch redhat`

### ISSUE THREAD

**Issue by LeosDing** [knqyf263/gost#41]
# gost fetch redhat
INFO[05-13|14:09:59] Initialize Database 
2020-05-13T14:09:59.849+0800	DEBUG	db path: db/trivy.db
2020-05-13T14:09:59.857+0800	DEBUG	remove an existed directory
[==============>     ] It will take a while for the first time... 2020-05-13T14:10:03.177+0800	DEBUG	error:  while accessing https://github.com/aquasecurity/vuln-list.git/info/refs

fatal: HTTP request failed

error in vulnerability DB initialize: error in vulnsrc clone or pull: failed to clone repository: error in git clone: failed to exec: exit status 128

**Comment by kotakanbe** [comment]
Closed because it cannot be reproduced.
